name = "coffee-dx"
compatibility_date = "2026-04-04"
main = "./workers/app.ts"
assets = { directory = "./build/client" }

[[d1_databases]]
binding = "DB"
database_name = "coffee-dx-db"
database_id = "548f7cf3-07db-4da6-b3a7-8f769d3a685d"

# Durable Objects
# [[durable_objects.bindings]]
# name = "ORDER_DO"
# class_name = "OrderDurableObject"
