name = "coffee-dx"
compatibility_date = "2024-04-01"
main = "build/server/index.js"
assets = { directory = "./build/client" }

# D1
# [[d1_databases]]
# binding = "DB"
# database_name = "coffee-dx"
# database_id = "YOUR_DATABASE_ID"

# Durable Objects
# [[durable_objects.bindings]]
# name = "ORDER_DO"
# class_name = "OrderDurableObject"
